// <auto-generated />
using System;
using MatchOddsService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MatchOddsService.Migrations
{
    [DbContext(typeof(MatchOddsServiceDbContext))]
    partial class MatchOddsServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MatchOddsService.Models.Entities.Match", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("MatchTime")
                        .HasColumnType("time(0)");

                    b.Property<int>("Sport")
                        .HasColumnType("int");

                    b.Property<string>("TeamA")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TeamB")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("MatchDate", "TeamA", "TeamB", "Sport")
                        .IsUnique();

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("MatchOddsService.Models.Entities.MatchOdds", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Odd")
                        .HasColumnType("decimal(9, 2)");

                    b.Property<int>("Specifier")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MatchId", "Specifier")
                        .IsUnique();

                    b.ToTable("MatchOdds");
                });

            modelBuilder.Entity("MatchOddsService.Models.Entities.MatchOdds", b =>
                {
                    b.HasOne("MatchOddsService.Models.Entities.Match", "Match")
                        .WithMany("MatchOdds")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
